services:
  web:
    build: .
    container_name: python-flask-server
    ports:
      - "5000:5000"  # Map container port 8000 to host 8000
    command: sh -c "flask --app main run --host=0.0.0.0 --port=5000"  # Bind to all interfaces
